# Generated by Django 4.0.6 on 2022-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_number', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('procedure', models.CharField(choices=[('l', 'loading'), ('u', 'unloading')], max_length=10)),
                ('warehouse', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1)),
                ('ramp', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9)], max_length=1)),
                ('registration_time', models.DateTimeField()),
                ('entry_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('r', 'registered'), ('e', 'entry'), ('d', 'departure')], max_length=1)),
            ],
        ),
    ]
