# Generated by Django 4.0.6 on 2022-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow', '0002_truck_operator_alter_truck_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='departure_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='entry_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
