# Generated by Django 4.0.6 on 2022-07-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow', '0004_alter_truck_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='operator',
        ),
        migrations.AlterField(
            model_name='truck',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='entry_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='state',
            field=models.CharField(max_length=1),
        ),
    ]
