# Generated by Django 4.0.6 on 2022-07-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow', '0005_remove_truck_operator_alter_truck_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='entry_time',
            field=models.DateTimeField(null=True),
        ),
    ]
