# Generated by Django 4.0.6 on 2022-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow', '0006_alter_truck_departure_time_alter_truck_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='command',
            field=models.CharField(choices=[('call', 'Вызвать'), ('entered', 'Въехал'), ('arrived', 'Прибыл'), ('serviced', 'Обслужен'), ('departure', 'Выехал')], max_length=10, null=True),
        ),
    ]
