# Generated by Django 4.0.6 on 2022-07-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow', '0007_truck_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='command',
            field=models.CharField(choices=[('call', 'Вызвать'), ('entered', 'Въехал'), ('departure', 'Выехал')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='departure_time',
            field=models.DateTimeField(blank=True, default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='entry_time',
            field=models.DateTimeField(blank=True, default=' '),
            preserve_default=False,
        ),
    ]
