# Generated by Django 4.0.6 on 2022-07-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow', '0008_alter_truck_command_alter_truck_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='command',
            field=models.CharField(blank=True, choices=[('call', 'Вызвать'), ('entered', 'Въехал'), ('departure', 'Выехал')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
