# Generated by Django 4.0.6 on 2022-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_flow', '0009_alter_truck_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='entry_time',
            field=models.DateTimeField(null=True),
        ),
    ]
